trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'

steps:
- task: RichCodeNavIndexer@0
  inputs:
    serviceConnection: 'rich-code-nav-prod'
    nugetServiceConnection: 'rich-code-nav-nuget'
    languages: 'cpp'
    githubServiceConnection: 'arjun27 (1)'
    serviceEndpoint: 'https://prod.richnav.vsengsaas.visualstudio.com'
